# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Planet_config = debug
  PlanetRuntime_config = debug
endif
ifeq ($(config),release)
  Planet_config = release
  PlanetRuntime_config = release
endif

PROJECTS := Planet PlanetRuntime

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Planet:
ifneq (,$(Planet_config))
	@echo "==== Building Planet ($(Planet_config)) ===="
	@${MAKE} --no-print-directory -C . -f Planet.make config=$(Planet_config)
endif

PlanetRuntime: Planet
ifneq (,$(PlanetRuntime_config))
	@echo "==== Building PlanetRuntime ($(PlanetRuntime_config)) ===="
	@${MAKE} --no-print-directory -C . -f PlanetRuntime.make config=$(PlanetRuntime_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Planet.make clean
	@${MAKE} --no-print-directory -C . -f PlanetRuntime.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Planet"
	@echo "   PlanetRuntime"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"